FROM node:18

LABEL version="1.0"
LABEL description="Base docker image for the City Science demo API."
LABEL maintainer = ["kdoykov99@gmail.com"] 


# ENV POSTGRES_DATABASE=${POSTGRES_DATABASE}
# ENV POSTGRES_HOST=${POSTGRES_HOST}
# ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
# ENV POSTGRES_URL=${POSTGRES_URL}
# ENV POSTGRES_URL_NON_POOLING=${POSTGRES_URL_NON_POOLING}
# ENV POSTGRES_USER=${POSTGRES_USER}
# ENV APP_SECRET=${APP_SECRET}
# ENV PROD=${PROD}
# ENV NODE_ENV=${NODE_ENV}
# ENV FILEBASE_KEY=${FILEBASE_KEY}
# ENV FILEBASE_SECRET=${FILEBASE_SECRET}
# ENV FILEBASE_BUCKET_NAME=${FILEBASE_BUCKET_NAME}
# ENV ALLOWED_ORIGINS=${ALLOWED_ORIGINS}

WORKDIR /usr/app
COPY ./ /usr/app

RUN yarn global add node-gyp
RUN yarn install --frozen-lockfile
COPY . .

EXPOSE 4000

CMD ["node","api/src/index.js"]