export default (sequelize, Sequelize) => {
  const TrafficData = sequelize.define("trafficData", {
    Count_point_id: Sequelize.INTEGER,
    Year: Sequelize.INTEGER,
    Region_id: Sequelize.INTEGER,
    Region_name: Sequelize.STRING,
    Region_ons_code: Sequelize.STRING,
    Local_authority_id: Sequelize.INTEGER,
    Local_authority_name: Sequelize.STRING,
    Local_authority_code: Sequelize.STRING,
    Road_name: Sequelize.STRING,
    Road_category: Sequelize.STRING,
    Road_type: Sequelize.STRING,
    Start_junction_road_name: Sequelize.STRING,
    End_junction_road_name: Sequelize.STRING,
    Easting: Sequelize.INTEGER,
    Northing: Sequelize.INTEGER,
    Latitude: Sequelize.DOUBLE,
    Longitude: Sequelize.DOUBLE,
    Link_length_km: Sequelize.DOUBLE,
    Link_length_miles: Sequelize.DOUBLE,
    Estimation_method: Sequelize.STRING,
    Estimation_method_detailed: Sequelize.STRING,
    direction_of_travel: Sequelize.STRING,
    Pedal_cycles: Sequelize.INTEGER,
    Two_wheeled_motor_vehicles: Sequelize.INTEGER,
    Cars_and_taxis: Sequelize.INTEGER,
    Buses_and_coaches: Sequelize.INTEGER,
    LGVs: Sequelize.INTEGER,
    HGVs_2_rigid_axle: Sequelize.INTEGER,
    HGVs_3_rigid_axle: Sequelize.INTEGER,
    HGVs_4_or_more_rigid_axle: Sequelize.INTEGER,
    HGVs_3_or_4_articulated_axle: Sequelize.INTEGER,
    HGVs_5_articulated_axle: Sequelize.INTEGER,
    HGVs_6_articulated_axle: Sequelize.INTEGER,
    All_HGVs: Sequelize.INTEGER,
    All_motor_vehicles: Sequelize.INTEGER,
  });
  return TrafficData;
};
