name: Test on last 2 major Node versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install
    - name: Run tests
      run: mocha
      env:
        POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
